apiVersion: v1
kind: Service
metadata:
  name: ihungo-backend
  namespace: ihungo
  labels:
    app: ihungo-backend
spec:
  type: NodePort
  selector:
    app: ihungo-backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
