# Generated by Django 5.1 on 2026-09-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_asociado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('workshop', 'Taller'), ('seminar', 'Seminario'), ('meeting', 'Reunión'), ('training', 'Capacitación'), ('other', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='users.asociado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
